### PR TITLE
Newsweek Clone Project

### PR DESCRIPTION
**Pull request by MuriloRoque**
In this project:

I worked alone;
Validated HTML;
Set up a code linter;
Used Bootstrap CSS classes.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @MuriloRoque, you have done a great job with this project 👍 README looks professional and PR looks great 😄 Let us address the following issues so we can work on it to improve our project:
Since the main purpose of this project is using bootstrap classes and making the project responsive, let fix the following:
* The use of bootstrap classes everywhere. Currently, our CSS file is large because we did not use much of the bootstrap classes. It is recommended for this project. Kindly check [bootstrap](https://getbootstrap.com/docs/4.1/getting-started/introduction/) documentation before we continue
bt
* ```Mobile device``` Currently this is how our nav looks on a mobile device and let us compare with the original
bmno
**Original**
bmn
* I realized the unresponsive behavior of the app on both the mobile and tablet mode. Kindly address this and compare with the original and fix the changes 👍 The following images were taken on both mobile and tablet mode when scrolling. Kindly check the images and address them.
mur
scroll-error
scroll-error3
scroll-error1
scroll-error2
* We currently have 50 warnings returned by HTML validator

Kindly fix these changes and submit another code review 🙂 
_Happy coding_ 👨‍💻 
Find Daniel Larbi Addo on Slack

**Comment by MuriloRoque** [comment]
Hello, thank you for the review.
I just changed everything you requested, and I added a lot more Bootstrap classes to the project.
I'm gonna wait for the next review, have a nice day!

**Comment by uryelah** [comment]
Hello **Murilo**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, great job adding bootstrap classes and fixing the overlap issues found in the last review.🎇**
I can see how much your project improved, nice touch with the tab icon by the way, and I know how amazing it will look in the end.

So get ready, stretch those typing-fingers and let's fix the remaining issues💪 

---------    

### Required changes 🛠 
---------

- [x]  Since bootstrap handles much of the project responsiveness and positioning this project needs to be an even closer clone the previous ones:
Screenshot_2020-03-23 Microverse Main Curriculum

So take some time to look at your clone and the[ original site](https://www.newsweek.com/) side by side and think try to catch differences in font, font-weight, color, positioning, etc.

--------

- [x] The navbar on small devices improved a lot but check how different your 'subscribe' button background is compared to the original one. Try to make it similar:
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology
**Original  nav:**
Screenshot_2020-03-23 Newsweek(7)

----------

- [x] On small widths your clone has a horizontal scroll problem. Check if there's any element that's wider than it should be or fix the issue with the `overflow` property.
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(1)


------

- [x] Pay attention to the font-weight and size of the article titles and it's text. Compare bellow your article and the original one:
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(2)
Screenshot_2020-03-23 Newsweek(8)

-----

- [x] On small screens the title of 'Latest News' should be to the right of the image. Compare your version and the original below:
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(3)
Screenshot_2020-03-23 Newsweek(9)

-----

- [x] Your 'Newsleter' image appears to be missing:
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(4)
Screenshot_2020-03-23 Newsweek(10)

------

- [x] On small widths your footer links text are wrapping while the ones on the original page don't.
Tip: try using the `white-space` property to avoid unwanted text wraps.
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(5)
Screenshot_2020-03-23 Newsweek(11)

--------

- [x] On medium-size screens the navbar is not as high, so you also need to reduce the margin/padding top of the main articles so you don't have empty space.
Compare your clone and the original page bellow: 
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(6)
Screenshot_2020-03-23 Newsweek(12)

------

- [x] On wide to medium screens the subscribe 'subscribe' magazine images are not positioned over one another like in the original site. Compare your 'Subscribe' section and the original one bellow: 
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(8)
Screenshot_2020-03-23 Newsweek(14)
------- 

- [x] On wide screens the sections above the 'In the magazine' section are all aligned in the bottom, without empty space and regardless if they are longer than the other. Try to use overflow or similar property to make it more like the original:
Screenshot_2020-03-23 Newsweek(15)
**Original site:**
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(9)

------

- [x] On wide screens the columns of three articles besides two bigger ones have a bigger image size in the original site. Compare your version and the original one.
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(10)
Screenshot_2020-03-23 Newsweek(16)


-----

- [x] Compare the titles font-size and weight from the original page footer to your clone. Make sure they are big enough and have a high enough weight.
Screenshot_2020-03-23 Newsweek - News, Analysis, Politics, Business, Technology(11)
Screenshot_2020-03-23 Newsweek(17)

--------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by mikenath223** [comment]
**Pull Request currently under review by MIchgolden Ukeje (TSE)**
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Awesome Job @MuriloRoque 👏👏
You've certainly made progress since the last review. 👍

However, there are still a few additional changes to be met before we proceed, some are from the previous review and some are few new observations:

**Changes [Required]** | **Screenshots**
------------------------ | -----------------
There is an overuse of the !important rule, note that as stated [here](https://speckyboy.com/good-bad-css-practices/) it should only be used when overriding third-party styles, but you used it even when not overriding third-party bootstrap styles. Try to correct that.
----------------------- | ------------------
The images in "IN THE MAGAZINE" section are far too large on mobile screens, consider reducing the size | **This is yours** 👇newsweek **This is the way it's supposed to be** 👇newsweek4
The social icons on mobile screen are too clumped together. Add spaces between them. | **This is yours** 👇newweek2
**This is the way it's supposed to be**👇newsweek5.
----------------- | --------------
Also on mobile screens, there is a visual hierarchy between the newsletter signup section and the footer section | **This is Yours**👇newsweek7 
**This is how it's supposed to be**👇newsweek6
**Changes [Optional]** | ------------------
Since this is a bootstrap focused project the use of plain CSS media queries is not encouraged you should try to achieve responsiveness mainly with bootstrap the documentation on bootstrap [flex methods](https://getbootstrap.com/docs/4.1/utilities/flex/) is a great place to start |

Kindly fix this issues and request another code review.
Feel free to reach out to me on Slack with the handle @mikenath223 
Best of luck 🎉🎉👍
Happy Coding 👨‍💻

**Comment by MuriloRoque** [comment]
Thanks for the review, I hope I can get better!
I think it is too late for me to use Bootstrap media query classes, I would have to make A LOT of changes, almost starting over.
I know this project is not the most well organized, I think I started it with the wrong foot and got lost through the process of making it, I promise I will get better!
Note: Please wait for 10 to 15 minutes after my last commit for my Live Link to work.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Nice work so far and for also making changes from previous reviews :clap: Your application looks good. I, therefore, approve of it. Congratulations :boom: :100:
### Required
- Make these images proportional, the width and height
images not proportional
### After implementing the change, submit your project. Good luck with the next project.
- Happy coding!

**Comment by MuriloRoque** [comment]
> Hello Team
> 
> ### Nice work so far and for also making changes from previous reviews 👏 Your application looks good. I, therefore, approve of it. Congratulations 💥 💯
> ### Required
> * Make these images proportional, the width and height
>   images not proportional
> 
> ### After implementing the change, submit your project. Good luck with the next project.
> * Happy coding!

@rOluochKe can you check the live link again? Maybe it wasn't updated yet, because on my screen they look proportional to all widths.

Thank you everyone for your review!

**Pull request merged**
